"""AgentCFD public engineering language."""

from . import (
    benchmarks,
    boundaries,
    capabilities,
    contracts,
    data_exchange,
    engineering,
    fluids,
    geometry,
    geometry_io,
    initialization,
    interoperability,
    meshing,
    outputs,
    parameters,
    postprocessing,
    procedures,
    projects,
    properties,
    providers,
    regions,
    studies,
    verification,
)
from ._version import __version__
from .model import Model, Step
from .interoperability import ScientificDatasetReader, open_scientific_dataset
from .projects import open_project
from .results import (
    Artifact,
    Check,
    FieldRecord,
    History,
    Quantity,
    SimulationResult,
    read_result_record,
)

__all__ = [
    "Artifact",
    "Check",
    "FieldRecord",
    "History",
    "Model",
    "Quantity",
    "SimulationResult",
    "ScientificDatasetReader",
    "Step",
    "__version__",
    "benchmarks",
    "boundaries",
    "capabilities",
    "contracts",
    "data_exchange",
    "engineering",
    "fluids",
    "geometry",
    "geometry_io",
    "initialization",
    "interoperability",
    "meshing",
    "outputs",
    "open_project",
    "open_scientific_dataset",
    "parameters",
    "postprocessing",
    "procedures",
    "properties",
    "projects",
    "providers",
    "regions",
    "studies",
    "verification",
    "read_result_record",
]
